### ISSUE TITLE
你好，想加入回落nginx的功能怎么修改呢?

### ISSUE THREAD

**Issue by Pacio** [jinmu333/docker-trojan-go#1]
https://github.com/lxhao61/integrated-examples/tree/main/trojan-go%5Ctrojan%2Bnginx

**Comment by dreamhunter2333** [comment]
最开始的版本已加入 nginx，会访问到nginx默认页，nginx 镜像换成自己网站的镜像即可
https://github.com/jinmu333/docker-trojan-go/blob/d7f7576f24748c9eb1fc1516fe8299bc5e99eecd/docker-compose.yml#L44

**Comment by Pacio** [comment]
> 最开始的版本已加入 nginx，会访问到nginx默认页，nginx 镜像换成自己网站的镜像即可
> 
> https://github.com/jinmu333/docker-trojan-go/blob/d7f7576f24748c9eb1fc1516fe8299bc5e99eecd/docker-compose.yml#L44

额，完全不懂docker，不会弄自己的镜像~不过还是谢谢，我试试不用docker直接部署上面的方案吧

**Comment by dreamhunter2333** [comment]
> > 最开始的版本已加入 nginx，会访问到nginx默认页，nginx 镜像换成自己网站的镜像即可
> > https://github.com/jinmu333/docker-trojan-go/blob/d7f7576f24748c9eb1fc1516fe8299bc5e99eecd/docker-compose.yml#L44
> 
> 额，完全不懂docker，不会弄自己的镜像~不过还是谢谢，我试试不用docker直接部署上面的方案吧

好吧，哈哈，我这个方案也可以的，有问题随时问， nginx 回落已经默认加入回落功能了

**Comment by Pacio** [comment]
> > > 最开始的版本已加入 nginx，会访问到nginx默认页，nginx 镜像换成自己网站的镜像即可
> > > https://github.com/jinmu333/docker-trojan-go/blob/d7f7576f24748c9eb1fc1516fe8299bc5e99eecd/docker-compose.yml#L44
> > 
> > 
> > 额，完全不懂docker，不会弄自己的镜像~不过还是谢谢，我试试不用docker直接部署上面的方案吧
> 
> 好吧，哈哈，我这个方案也可以的，有问题随时问， nginx 回落已经默认加入回落功能了

你好，试了一下你这个，执行bash init.sh直接报错了，如下：
sed: can't read s/your_site/site.com/g: No such file or directory
